### ISSUE TITLE
封面图片

### ISSUE THREAD

**Issue by TonyZYT2000** [random-yang/paper#18]
作者好！谢谢您的主题！
我看到您的博客有一篇文章是有封面图片的。请问如何添加封面图片呢？

**Comment by random-yang** [comment]
@TonyZYT2000 
在README里面有写的哦
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/25839518/77275130-822b9080-6cf2-11ea-8921-2489bcd24b73.png">

比如你的markdown顶部
photos:
- image-url(一般是外链)

**Comment by TonyZYT2000** [comment]
懂了，之前看漏了，感谢！
