### ISSUE TITLE
Code highlighting not working in Firefox

### ISSUE THREAD

**Issue by RohanGautam** [random-yang/paper#21]
# Chrome : 
![Screenshot from 2020-03-24 21-44-45](https://user-images.githubusercontent.com/17317792/77432242-c4e78880-6e18-11ea-84c7-7be00250e0ac.png)
# Firefox :
![Screenshot_2020-03-24 Hello World   Rohan's Blog ](https://user-images.githubusercontent.com/17317792/77432273-ce70f080-6e18-11ea-8c99-e30f899be7bd.png)

The code highlighting only seems to work on chrome! I really like this theme, is there any fix?

**Comment by random-yang** [comment]
@RohanGautam Hi, I am sorry this happened, I will fix this issue as soon as possible! Thanks!

**Comment by random-yang** [comment]
@RohanGautam Hi, this problem seems to be fixed. Check it out at least master version and thanks for your valuable issue.😃
If there is no questions further, I will close this issue.

**Comment by RohanGautam** [comment]
It's working on the latest version! Thanks a lot for your fast response.
I'll close the issue!
