### ISSUE TITLE
hexo new page 不起作用

### ISSUE THREAD

**Issue by wildplant** [random-yang/paper#24]
谢谢您做的主题，很漂亮。

我新建页面，可以访问，但是主体内容没有渲染出来。

**Comment by random-yang** [comment]
@hello, 能否方便提供更多的信息呢，比如运行 `hexo new xxx`后有没有什么报错，或者是`hexo s`能不能成功在本地起服务预览页面等等。麻烦提供更多的信息，我好帮你解决哈。

**Comment by wildplant** [comment]
谢谢，没有报错。我运行hexo new page "xxx"后，在public也出现了xxx/index.md，也可以访问/xxx，但出现类似于您网站 http://randomyang.top/about/  的效果。只有右边的侧边栏能显示出来。主体内容不显示。

**Comment by random-yang** [comment]
@wildplant 抱歉没能复现你的情况。
