### ISSUE TITLE
求下一版本添加修改字体，喜欢作者博客的字体。

### ISSUE THREAD

**Issue by thejtf** [random-yang/paper#25]
感谢大佬的主题

**Comment by random-yang** [comment]
@thejtf 好的，我只是在我自己的blog测试，后面稳定了确定不会影响加载速度的时候，我会更新到master的😀。

**Comment by thejtf** [comment]
> @thejtf 好的，我只是在我自己的blog测试，后面稳定了确定不会影响加载速度的时候，我会更新到master的😀。

补充提问：我看主题里面默认是Noto Serif SC这个字体，但是为啥我的blog却一直是Helvetica Neue啊，这个问题该如何解决呢？
