### ISSUE TITLE
如何开启评论功能？

### ISSUE THREAD

**Issue by thejtf** [random-yang/paper#26]
在comments-script.pug里修改为自己的appId和appKey后，不起作用，是还有哪里需要设置嘛，请问大佬如何配置才能正确开启呢？

**Comment by random-yang** [comment]
@thejtf  Hi, 我提交更新了一个版本在master，更新你的本地代码后，根据这个配置：
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/25839518/77985107-17a7cf80-7346-11ea-8276-8e2fcb2b9f4c.png">

**Comment by thejtf** [comment]
> @thejtf Hi, 我提交更新了一个版本在master，更新你的本地代码后，根据这个配置：
> <img alt="image" width="1013" src="https://user-images.githubusercontent.com/25839518/77985107-17a7cf80-7346-11ea-8276-8e2fcb2b9f4c.png">

好的，谢谢大佬。

**Comment by thejtf** [comment]
> @thejtf Hi, 我提交更新了一个版本在master，更新你的本地代码后，根据这个配置：
> <img alt="image" width="1013" src="https://user-images.githubusercontent.com/25839518/77985107-17a7cf80-7346-11ea-8276-8e2fcb2b9f4c.png">

按照提示配置好了，没反应还是。[](https://imgkr.cn-bj.ufileos.com/281b0252-adeb-46e2-a0a2-46d311dae1d3.png)

**Comment by thejtf** [comment]
> @thejtf Hi, 我提交更新了一个版本在master，更新你的本地代码后，根据这个配置：
> <img alt="image" width="1013" src="https://user-images.githubusercontent.com/25839518/77985107-17a7cf80-7346-11ea-8276-8e2fcb2b9f4c.png">

只是修改_config.yml里面的

`# commend module
comment:
  enable: true
  appId: **************
  appKey: *************
  placeholder: say something
  notify: false
  verify: false
  avatar: mp`
 以上设置对吧，但是我配置上还是没反应。

**Comment by random-yang** [comment]
@thejtf 能正常用了吗？

**Comment by thejtf** [comment]
> @thejtf 能正常用了吗？

还是没有成功开启评论功能

**Comment by thejtf** [comment]
> @thejtf 能正常用了吗？

我还是试图重新安装了一遍主题，还是老样子。。

**Comment by thejtf** [comment]
@random-yang 还是不行，我还是试图重新安装了一遍主题，还是老样子。。

**Comment by random-yang** [comment]
@thejtf 抱歉，上午改得太匆忙了，你现在再拉最新的试试呢～

**Comment by thejtf** [comment]
@random-yang 您是又提交了嘛，我没有看到更新啊

**Comment by random-yang** [comment]
@thejtf  忘了点merge🤣，sorry man.

**Comment by thejtf** [comment]
@random-yang 这次终于好啦👏

**Comment by random-yang** [comment]
如果觉得主题不错，麻烦小星星欧～
