### ISSUE TITLE
Code render scrolling issue

### ISSUE THREAD

**Issue by RohanGautam** [random-yang/paper#30]
![Screenshot from 2020-04-03 22-06-29](https://user-images.githubusercontent.com/17317792/78369291-85c6ed80-75f7-11ea-8a53-c7edb583aefb.png)
When the code block is long, the user is unable to scroll sideways in the resultant render.
Issue persists on both Firefox and Chrome.
Any idea?

**Comment by random-yang** [comment]
@RohanGautam OK, got it ! I'll check this as soon as possible.

**Comment by random-yang** [comment]
@RohanGautam Hi, I check it at the latest master version. I seems worked. Maybe you could try the latest version. 
I am sorry that I forgot to mention the update in my doc.😅

<img width="696" alt="image" src="https://user-images.githubusercontent.com/25839518/78371758-f9b6c500-75fa-11ea-976e-bf7ecae0984f.png">

**Comment by random-yang** [comment]
@RohanGautam Hello, is the problem solved? If solved, please close this issue, thx.

**Comment by RohanGautam** [comment]
That's very weird! I pulled the latest version and it didnt work for me.
To double check, i deleted my `themes/paper` directory and did a fresh clone. But the error still persisted:
![image](https://user-images.githubusercontent.com/17317792/78469592-41516400-7755-11ea-9894-536b63811e6c.png)

Do you think it is an OS thing? because I experience this on both Firefox and Chrome. I'm using Pop_OS 19.10 on a Thinkpad X1 Extreme.

**Comment by random-yang** [comment]
@RohanGautam I made some fix, try again?

**Comment by RohanGautam** [comment]
![image](https://user-images.githubusercontent.com/17317792/78518129-24b73980-77f2-11ea-98e6-e39549e6d890.png)
Can see the scrollbar now! Thank you ! :D I will proceed to close the issue.
