### ISSUE TITLE
landscape设计

### ISSUE THREAD

**Issue by chinobing** [random-yang/paper#32]
有没有想过做像anyway那种全版面设计？

**Comment by random-yang** [comment]
@chinobing  啊哈？你好，此话怎讲，可以描述得更具体一点吗？你是说布局还是什么呢。

**Comment by chinobing** [comment]
就是全屏展示内容.没事，就建议一下

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by random-yang** [comment]
嗯嗯，了解了一下。最好的方法是，直接征得anyway的同意，将他们的设计转化为一个可以用的blog主题模版，不然可能会被指抄袭😅。
