### ISSUE TITLE
关于客制化

### ISSUE THREAD

**Issue by Gnomeek** [random-yang/paper#34]
你好，我想在侧边栏里新增一个about me的超链接，应该修改主题文件源代码的哪一部分？

**Comment by random-yang** [comment]
关于你说的这个功能，有一种方法就是通过下面三步：
1. 在`themes/paper/_config.yml`中添加一下内容：
<img width="462" alt="image" src="https://user-images.githubusercontent.com/25839518/81036353-64487280-8ed1-11ea-9abc-33bc99edd35f.png">

2. 然后创建这个结构的文件：
<img width="180" alt="image" src="https://user-images.githubusercontent.com/25839518/81036388-83df9b00-8ed1-11ea-8297-103f9ef301bb.png">
在 `index.md`中写 about me 页面的内容

3. 最后的效果：
<img width="259" alt="image" src="https://user-images.githubusercontent.com/25839518/81036367-73c7bb80-8ed1-11ea-99ec-38955548185f.png">

当然如果你不满意这种解决，可以修改`themes/paper/layout/includes/sidebar.pug`的内容（不过可能会麻烦很多了）

**Comment by Gnomeek** [comment]
感谢！
