### ISSUE TITLE
关于移动端布局出错

### ISSUE THREAD

**Issue by Gnomeek** [random-yang/paper#35]
我按照issue #34 里的方法创建了About Me界面，在桌面端显示正常，而在移动端布局就变乱了，详情见下图。
![image](https://user-images.githubusercontent.com/19972493/81171487-0b5f0400-8fcf-11ea-9fce-b6077e4f9443.png)
想问下这种情况该怎么解决，感谢。/cc @random-yang

**Comment by Gnomeek** [comment]
![image](https://user-images.githubusercontent.com/19972493/81172533-00a56e80-8fd1-11ea-8af7-e843c05e8803.png)
问题应该是出在sidebar上，但是我对比了About Me界面和普通文章界面（普通文章移动端响应布局正常），两者的css样式并没有区别...

**Comment by Gnomeek** [comment]
另一个问题是，我在link中添加的链接（除了模板中提供的那些），比如steam，点击链接会导至mysite.github.io/实际的链接，而不是直接打开实际网站。

**Comment by random-yang** [comment]
@Gnomeek 好的，感谢反馈，我尽快修复，给你答复～

**Comment by random-yang** [comment]
关于你提出的第二个问题，我测试了一下感觉好像是没有问题的。不知道是我理解错了你的场景还是还是什么问题。你可以看看：

- 修改`theme/paper/_config.yml`:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/25839518/81177170-d192fb00-8fd8-11ea-99c9-6fee7a35e8d3.png">

- 渲染结果：
<img width="300" alt="image" src="https://user-images.githubusercontent.com/25839518/81177243-ea9bac00-8fd8-11ea-9510-8cc26c033cfd.png">

- 点击*Steam*跳转到：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25839518/81177343-1028b580-8fd9-11ea-891f-427cd4b9d0ac.png">

**Comment by Gnomeek** [comment]
第二个问题是我的问题.. steam用的是https，我的url填成http的了..

**Comment by random-yang** [comment]
@Gnomeek 第一个问题我似乎修复了，你再拉master试试～

**Comment by Gnomeek** [comment]
可以了，感谢
