### ISSUE TITLE
黑天方式很有问题 会造成后续加载的图片节点无法正常显示

### ISSUE THREAD

**Issue by instkffff** [random-yang/paper#39]
你那个黑天模式反转图片颜色的函数，只能影响静态文件的网页图片元素，给他们加滤镜，后加载的就加不上了，然后全局反色后，就不对了。

我建议开启黑天模式时在全局css增加 

``` css
img {filter: invert(100%)}
```

来确保避免这个问题

### 问题图片示例

![image](https://user-images.githubusercontent.com/3518214/83051559-c6376a80-a080-11ea-9be1-68f89b8a59f5.png)

-----------------------------

你这个黑天模式很偷懒，希望完善成正经的黑天模式，加载另一套颜色配置文件，而非反色。

**Comment by random-yang** [comment]
@instkffff 是的，你提到的图片问题确实存在，需要监听DOM的更变才能解决。或者是用css变量。不过都不是很好的方法啦。总之还是需要重新设计暗黑模式，更换整体的样式。后续有重新设计暗黑模式的打算。
