### ISSUE TITLE
文章索引栏还有点显示的小问题

### ISSUE THREAD

**Issue by instkffff** [random-yang/paper#42]
很显然 我划红框的地方有点不等宽 可能不太美观（个人感觉） 建议把 .tocbot加个margin-bottom: 1.6rem; 就好了

![image](https://user-images.githubusercontent.com/3518214/83056753-85435400-a088-11ea-9b2f-8ccbbd8519e9.png)

**Comment by random-yang** [comment]
@instkffff 感谢反馈，已修复
