### ISSUE TITLE
开启文章摘录导致页面布局混乱

### ISSUE THREAD

**Issue by jjsay** [random-yang/paper#48]
当通过使用 more 注释并给文章设定摘录后，右侧边栏位置从原来的位置移动到了文章列表底部。

**Comment by random-yang** [comment]
@zwzwclub 不知道您的情况是什么，麻烦截图说明一下。 刚刚看了一下确实有问题，特别是当有图片的时候，不过现在已经修复。

**Comment by zwzwclub** [comment]
> @zwzwclub 不知道您的情况是什么，麻烦截图说明一下。 刚刚看了一下确实有问题，特别是当有图片的时候，不过现在已经修复。

https://i.loli.net/2020/08/04/DVo7t4Gg93RkCBp.png
P1：没有使用****时候的正常页面；
https://i.loli.net/2020/08/04/vwZWmrRy6iGXL4H.png
P2：添加****，显示摘录
https://i.loli.net/2020/08/04/znoGUhq29t7bkJs.png
P3：****注释前同时包含文字和图片
https://i.loli.net/2020/08/04/obNBvszipO1hKQd.png
P4：****注释前只有文字

**Comment by zwzwclub** [comment]
> @zwzwclub 不知道您的情况是什么，麻烦截图说明一下。 刚刚看了一下确实有问题，特别是当有图片的时候，不过现在已经修复。

`<!--more-->`

**Comment by random-yang** [comment]
@zwzwclub 你已经更新了最新的master了嘛

**Comment by zwzwclub** [comment]
> @zwzwclub 你已经更新了最新的master了嘛

我先更新下试试，如有其它问题后续再反应

**Comment by zwzwclub** [comment]
> @zwzwclub 你已经更新了最新的master了嘛

刚才更新后，问题还在。回头我再初始化一个项目测试下；另外，默认页码显示移动适配值得调整下：
![](https://i.loli.net/2020/08/04/ZvxEP4TrsVW3hc1.png)
当然，我是修改过了：
![](https://i.loli.net/2020/08/04/ZvxEP4TrsVW3hc1.png)

**Comment by jjsay** [comment]
> @zwzwclub 你已经更新了最新的master了嘛

已确认修复啦~~
