### ISSUE TITLE
LaTeX支持问题

### ISSUE THREAD

**Issue by AntiZpvoh** [random-yang/paper#52]
在尝试根据博文 https://blog.csdn.net/weixin_44191286/article/details/102702479 构建可显示LaTeX公式的博客时失败，无法显示公式，如下图：
<img width="653" alt="Screen Shot 2020-09-29 at 12 04 07 AM" src="https://user-images.githubusercontent.com/59728467/94457557-4e707c80-01e7-11eb-800a-73af2f68f4ef.png">
使用landscape时可以看见：
<img width="885" alt="Screen Shot 2020-09-29 at 12 05 21 AM" src="https://user-images.githubusercontent.com/59728467/94457658-795ad080-01e7-11eb-97ea-c0f835e8abbe.png">
大佬这个有什么解决方案吗？

**Comment by random-yang** [comment]
@AntiZpvoh 好的，之后给你反馈

**Comment by random-yang** [comment]
@AntiZpvoh 拉取最新的master再试试，具体配置看README
![image](https://user-images.githubusercontent.com/25839518/94524605-6be42b80-0265-11eb-85c4-5a1f934fa9e7.png)

**Comment by AntiZpvoh** [comment]
感谢！我试一试

**Comment by random-yang** [comment]
@AntiZpvoh 你好，如果没什么问题，我就关issue了

**Comment by AntiZpvoh** [comment]
@random-yang 嗯嗯没啥问题
