### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by noraj** [random-yang/paper#56]
Is it possible to have a readme in english please?

**Comment by random-yang** [comment]
@noraj Yes, of course. But, You may have to wait for a while. Please subscribe, If it's ok, I'll notice you.

**Comment by random-yang** [comment]
@noraj Hello.
En-version is here: https://github.com/random-yang/paper/blob/master/README.en.md.
Hope it's not too late.

**Comment by noraj** [comment]
Thx this will help a lot.
