### ISSUE TITLE
浏览器tab页面的头像

### ISSUE THREAD

**Issue by brandon0824** [random-yang/paper#58]
你好 非常喜欢这个主题 想请教浏览器tab页面那个favicon.ico去哪里修改
我修改了themes\paper\source\favicon.ico没有生效 是不是有其他的方法

**Comment by random-yang** [comment]
@brandon0824 你好，通常来说，直接替换 favicon.ico 就可以了。你可以尝试**强制刷新**页面看看(有可能是缓存了之前的ico).还有就是检查一下你的图片格式是否正确。

**Comment by brandon0824** [comment]
谢谢回复 问题已经解决了~
