### ISSUE TITLE
无法更改主题色

### ISSUE THREAD

**Issue by Kai2510** [random-yang/paper#62]
您好！感谢您做出这么好看的主题，简洁而又有点书卷气，我很喜欢。但是在yml文件中更改main_color时，无论如何更改都不影响渲染出的网页的主题色。想请教一下，应如何配置？

**Comment by random-yang** [comment]
你好，你是填写的这几个当中的一个吗？
![image](https://user-images.githubusercontent.com/25839518/161372119-b783058f-edde-412d-b2be-4c798009151f.png)

**Comment by Kai2510** [comment]
不好意思，今天再次生成的时候就正常了。可能是因为重新安装了hexo-renderer-marked或hexo-renderer-pug或hexo-developer-kit的原因。
另外，想请教一下，主题的footer文件应该如何写？我想在里面插入备案的图标。
非常感谢！

**Comment by Kai2510** [comment]
是的，几种都试了。后来自己往css里加了变量，起了个名，也不行。Hexo 6.1.0。也许是缺插件？在装插件的时候npm audit提示有几处vulnerabilities，可能有关？
目前除了颜色不能改之外都正常。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月2日 15:28
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [random-yang/paper] 无法更改主题色 (Issue #62)


你好，你是填写的这几个当中的一个吗？
[image]<https://user-images.githubusercontent.com/25839518/161372119-b783058f-edde-412d-b2be-4c798009151f.png>

―
